### ISSUE TITLE
Text-image - Espacements

### ISSUE THREAD

**Issue by gjphenry** [whitecube/laravel-preset#19]
Rectification :
- 8px entre le titre et le texte ;
- pas de wysiwyg comme texte, c'est la porte ouverte aux folies.

**Comment by theokbokki** [comment]
C'est @toonvandenbos qui m'a demandé de mettre un wysiwyg. Ce sera un wysiwyg simplifié

Je vous laisse en débatre entre vous 🥊

**Comment by toonvandenbos** [comment]
Le wysiwyg c'est juste une question de flexibilité, au final c'est nous qui décidons ce qui sera injecté comme contenu au cas par cas. Donc laissons le wysiwyg mais précisons dans la notice d'utilisation qu'il faut l'éviter

**Comment by gjphenry** [comment]
Ce qu'on peut laisser faire à la limite c'est :
- mettre en gras un élément ;
- mettre en italic un élément ;
- mettre un lien (mais c'est dangereux niveau start) ;

Ce qu'il faut surtout pas : 
- pouvoir passer à la ligne (les margins cassent tout le design et ne sont pas prévue pour cet emplacement) ;
- mettre des images et vidéos ;
- faire des tableaux ;
- faire des listes à puces ;
- etc...

**Comment by theokbokki** [comment]
Closed by [#10](https://github.com/whitecube/laravel-preset-site/pull/10)
