### ISSUE TITLE
Global - Responsive

### ISSUE THREAD

**Issue by gjphenry** [whitecube/laravel-preset#22]
Il y a un problème avec un élément insécable dans le design de la page qui empêche le contenu de s'adapter correctement à la taille du viewport à partir de 796px sur la page des text-image.

Ca facilite pas la review

**Comment by theokbokki** [comment]
Tu parles de ça?

<img width="773" alt="image" src="https://github.com/whitecube/laravel-preset/assets/90846584/3ee63c17-f061-41ac-86c3-dc086272fd60">

**Comment by gjphenry** [comment]
Yesss, ça fait tout casser dans mon inspecteur quand je resize

**Comment by theokbokki** [comment]
Closed by [#7](https://github.com/whitecube/laravel-preset-site/pull/7)
