### ISSUE TITLE
Header - Espacements

### ISSUE THREAD

**Issue by gjphenry** [whitecube/laravel-preset#24]
- Même remarques concernant le WYSIWYG, ici je vois un retour à la ligne qui ne devrait pas être possible. Si une segmentation en paragraphe doit se faire, ça sera designé au préalable ;
- header label 20px de margin-top ;
- header txt 20px de margin-top ;
- header container 100px de padding-bottom ;
- si le header est sensé prévoir un espace pour la navigation qui serait placée en absolute sur celui-ci, alors mettre le padding-top à 180px, sinon, laisser comme ça

**Comment by theokbokki** [comment]
Closed by [#9](https://github.com/whitecube/laravel-preset-site/pull/9)
