### ISSUE TITLE
WYSIWYG - Responsive

### ISSUE THREAD

**Issue by gjphenry** [whitecube/laravel-preset#27]
Margins latéraux du layout wysiwyg container : 
- 920vw -> Une seule colonne de margin à droite et à gauche
- 640vw -> margin 0

Attention que ça risque d'évoluer lorsque les blocs images et vidéos seront intégrés

**Comment by theokbokki** [comment]
Closed by [#8](https://github.com/whitecube/laravel-preset-site/pull/8)
